language: python
branches:
    only:
        - master
        - develop
        
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
install:
    - pip install -r requirements-dev.txt
    - pip install coveralls
script:
    - py.test --cov=pyswag --cov-config=.coveragerc pyswag/tests
after_success:
    - coveralls

